#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog',     url: 'blog'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'DALLE2',   url: 'dalle2-pytorch', short_description: 'Training the next generation of visual generative models'}
- {name: 'Mind Reading', url: 'mind-reading', short_description: 'Recreating images from MRI scans'}
- {name: 'Multi-Agent Control',   url: 'multi-agent-control', short_description: 'Solving the task assignment problem for robust high abstraction goal completion'}
- {name: 'Truss Solver',   url: 'truss-solver' }
- {name: 'UToronto Downloader',   url: 'utoronto-downloader', short_description: 'Popular WebExtension to allow students to download their lectures' }


#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/veldrovive'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/aidan-dempster-4b3444179/'}
- {icon: 'envelope',  link: 'mailto:mailto:aidan.dempster@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Aidan Dempster - Personal Portfolio '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-analytics-ua: ''
google-analytics-tag: 'G-7KD685VS65'
#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
